<a href="https://colab.research.google.com/github/tsaiyftw/python_ML_401/blob/main/class_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [65]:
class Person:
  # constructor 
  
  def __init__(self,name,gender):
    self.n = name
    self.g= gender
    print("This is a person class")
  # instance method 
  def introduction(self):
    print(f"I am {self.n}")

In [17]:
p1 = Person("Yifang", "female")
p2 = Person("JJ", "male")

This is a person class
This is a person class


In [15]:
print(p1.n,p1.g)
print(p2.g,p2.n)

Yifang female
male JJ


In [19]:
p1.introduction()
p2.introduction()

I am Yifang
I am JJ


In [10]:
class Worrior:
  # define object's properties( or fields, or attributes)
  def __init__(self, name, gender, weapon = "bat"):
    self.lv = 1
    self.exp =0
    self.n = name
    self.g = gender
    self.w = weapon
    print("This is the worrior class")
  # show the obbject properties instead of " __main__ at address to the address"
  def __str__(self):
    return f"Name:{self.n}, Level:{self.lv}, Experience:{self.exp},  Gender:{self.g}, Weapon:{self.w}"
  def introduction(self):
    return f"I am {self.n} and my weapon is {self.w}"
  def attack(self, enemy):
    self.exp += 50
    self.level_up()
    enemy.hp -=1
    return f"{self.n} attacking! now exp is {self.exp} and level is {self.lv}"
  def level_up(self):
    if self.exp >= 100:
      self.lv += 1
      self.exp -=100
      print(f"{self.n} Level UP!!!")

class Enemy:
  def __init__(self):
    self.n = "Moster"
    self.hp = 100
    print("This is the Enemy class")

In [11]:
w1 = Worrior( name ="JJ", weapon="sword", gender="M")
print(w1)
w2 =Worrior(name="KK", gender="F", weapon="longbow")
print(w2.introduction())

e= Enemy()


This is the worrior class
Name:JJ, Level:1, Experience:0,  Gender:M, Weapon:sword
This is the worrior class
I am KK and my weapon is longbow
This is the Enemy class


In [18]:
for i in range(5):
  print(w1.attack(e))
e.hp

JJ attacking! now exp is 50 and level is 16
JJ Level UP!!!
JJ attacking! now exp is 0 and level is 17
JJ attacking! now exp is 50 and level is 17
JJ Level UP!!!
JJ attacking! now exp is 0 and level is 18
JJ attacking! now exp is 50 and level is 18


65

In [75]:
class Charactor:
  def __init__(self,name, gender, weapon="bat"):
    self.lv = 1
    self.exp = 0
    self.n = name
    self.g = gender
    self.w = weapon
    print("This is the Charactor class")
  def __str__(self):
    return f"Name:{self.n}, Gender: {self.g}, Weapon:{self.w}, Level:{self.lv}, Exp:{self.exp}"
  def attack(self, enemy):
    self.exp += 50
    self.level_up()
    enemy.hp -=1
    return f"{self.n} attacking! now exp is {self.exp} and level is {self.lv}"
  def level_up(self):
    if self.exp >= 100:
      self.lv += 1
      self.exp -=100
      print(f"{self.n} Level UP!!!")

class Enemy:
  def __init__(self):
    self.n = "Moster"
    self.hp = 100
    print("This is the Enemy class")

class Worrior(Charactor):
  def __init__(self,name_n, gender_n, weapon_n):
    super().__init__(name_n, gender_n, weapon_n)
    self.sp = 100
    print("This is the worrior class")
  def attack(self,enemy):
    super().attack(enemy)
    return f"Adding something else to super class method"

class Masician(Charactor):
  def __init__(self,name, gender, weapon):
    super().__init__(name,gender, weapon)
    self.mp = 100
    print("This is the masician class")

In [71]:
w1 = Worrior(name_n = "RR", gender_n = "F", weapon_n ="stone")
m1 = Masician(name = "LL", gender = "M", weapon ="Flying")

This is the Charactor class
This is the worrior class
This is the Charactor class
This is the masician class


In [72]:
print(m1)
print(w1)

Name:LL, Gender: M, Weapon:Flying, Level:1, Exp:0
Name:RR, Gender: F, Weapon:stone, Level:1, Exp:0


In [73]:
e = Enemy()

This is the Enemy class


In [74]:
for i in range(5):
  print(w1.attack(e))

Adding something else to super class method
RR Level UP!!!
Adding something else to super class method
Adding something else to super class method
RR Level UP!!!
Adding something else to super class method
Adding something else to super class method


In [2]:
import numpy as np

# a = [1,2,3]
# b = [4,5,6]

# arr_a = np.array(a)
# arr_b = np.array(b)

# print(arr_a+ arr_b)

In [79]:
a = np.array([1,2,3])
b = np.array([[1.0,2.0,3.0],[3.2,5.7,8.2]])
print(f"a: {a}")
print(f"a dimension: {a.ndim}")
print(f"a shape: {a.shape}")
print(f"a type: {a.dtype}")
print(f"b: {b}")
print(f"b dimension: {b.ndim}")
print(f"b shape: {b.shape}")
print(f"b type: {b.dtype}")

a: [1 2 3]
a dimension: 1
a shape: (3,)
a type: int64
b: [[1.  2.  3. ]
 [3.2 5.7 8.2]]
b dimension: 2
b shape: (2, 3)
b type: float64


In [80]:
a = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(a[0,]) # 6
print(a[1,:]) # [7,8,9,10,11,12]
print(a[:,4]) # [5,11]
print(a[1,2:6:2]) # [9,11] (start,stop,step)
a[1,2] = 20
print(a)
a[:,2] = [7,8]
print(a)

[1 2 3 4 5 6]
[ 7  8  9 10 11 12]
[ 5 11]
[ 9 11]
[[ 1  2  3  4  5  6]
 [ 7  8 20 10 11 12]]
[[ 1  2  7  4  5  6]
 [ 7  8  8 10 11 12]]


In [3]:
a = np.array([[92,83,56,77,98],[81,53,64,76,60]])
print(a)
print(np.max(a,axis=0))
print(np.max(a,axis=1))
print(np.sum(a,axis=0))
print(np.sum(a,axis=1))

[[92 83 56 77 98]
 [81 53 64 76 60]]
[92 83 64 77 98]
[98 81]
[173 136 120 153 158]
[406 334]
